[lint]
ignore = [
    "E501",
    "COM812",
    "PLR0911",
    "PLR0912",
    "PLR0915",
]
select = [
    "A",
    "ANN",
    "ARG",
    "B",
    #"BLE",
    "C4",
    #"C90",
    "COM",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "G",
    "FLY",
    "FURB",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PLR",
    #"PT",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TID",
    "TRY",
    "W",
]